language: php
sudo: required
dist: trusty
group: edge
php:
  - 7.1
  - hhvm
  - nightly

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

install:
  - composer selfupdate

before_script:
  - if [[ $TRAVIS_PHP_VERSION != hhvm* ]]; then composer install -n --prefer-source; else composer install -n --prefer-source --ignore-platform-reqs; fi

script:
  - mkdir -p build/logs
  - phpunit

after_script:
  - if [[$(phpenv version-name) != "nightly" && $(phpenv version-name) != "hhvm"]]; then CODECLIMATE_REPO_TOKEN=4295b7489478a4fea3966d5391d34864af8168e91efeacc76402aeed0453be66 ./vendor/bin/test-reporter --stdout > codeclimate.json; fi
  - "if [[$(phpenv version-name) != 'nightly' && $(phpenv version-name) != 'hhvm']]; then curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.1)' https://codeclimate.com/test_reports"
