language: php
php:
  - 5.6

install:
  - composer install

script:
  - mkdir -p build/logs
  - phpunit

after_script:
  - CODECLIMATE_REPO_TOKEN=4295b7489478a4fea3966d5391d34864af8168e91efeacc76402aeed0453be66 vendor/bin/test-reporter
