language: php
php:
  - 5.6

install:
  - composer install

script:
  - mkdir -p build/logs
  - phpunit

after_script:
  - CODECLIMATE_REPO_TOKEN=4295b7489478a4fea3966d5391d34864af8168e91efeacc76402aeed0453be66 ./vendor/bin/test-reporter --stdout > codeclimate.json
  - "curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.1)' https://codeclimate.com/test_reports"
