language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm
  - nightly

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

matrix:
  allow_failures:
    - php: hhvm
    - php: nightly
  fast_finish: true

before_install:
  - apt-key adv --keyserver hkp://hkps.pool.sks-keyservers.net --recv-keys D59097AB
  - echo "deb http://packages.blackfire.io/debian any main" > /etc/apt/sources.list.d/blackfire.list
  - apt-get update
  - apt-get install -y blackfire-agent
  - apt-get clean && rm -rf /var/lib/apt/lists/*

install:
  - composer selfupdate
  - composer install

script:
  - mkdir -p build/logs
  - phpunit

after_script:
  - if [ "`php -m | grep -i xdebug`" ]; then CODECLIMATE_REPO_TOKEN=4295b7489478a4fea3966d5391d34864af8168e91efeacc76402aeed0453be66 ./vendor/bin/test-reporter --stdout > codeclimate.json; fi
  - "curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.1)' https://codeclimate.com/test_reports"
